#!/usr/bin/env python
"""Run the benchmark on a Kaggle GPU and pull the results back.

Why this exists: the dev laptop has a GTX 1650 (4 GB, fp16 broken, VRAM spills into system RAM).
Kaggle gives a 16 GB T4/P100 on Linux, which produces real batch sweeps, a real fp16-vs-fp32
answer, and real OOM instead of silent paging. It is still not the target 24 GB card (H-001).

    python tools/kaggle_bench.py push      # create/update the kernel and start it
    python tools/kaggle_bench.py status    # poll
    python tools/kaggle_bench.py fetch     # download results into eval/runs/<name>/
    python tools/kaggle_bench.py delete    # remove the kernel from your account

Credentials: this talks to the **legacy** REST API at www.kaggle.com/api/v1, not the newer
api.kaggle.com host, which is network-blocked from Iran (403 from Google's frontend). That also
makes the new `KGAT_...` tokens unusable, because the CLI validates them against the blocked host.
So we use the classic username + key from ~/.kaggle/kaggle.json or KAGGLE_USERNAME/KAGGLE_KEY.

The kernel is **private** and clones this repo at a pinned commit, so whatever you push to GitHub
is what gets benchmarked.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://www.kaggle.com/api/v1"
REPO_URL = "https://github.com/Pouyops/Seller_Tooling.git"
DEFAULT_SLUG = "seller-tooling-bench"
DATASET_NAME = "synth-v1-s1403-n200"


STATE = ROOT / ".kaggle-run.json"


def remember_slug(slug: str, url: str, commit: str) -> None:
    STATE.write_text(json.dumps({"slug": slug, "url": url, "commit": commit, "at": time.time()}, indent=2), encoding="utf-8")


def resolve_slug(given: str | None) -> str:
    """Kaggle derives the real slug from the *title*, ignoring the slug we ask for, so trust what
    the push returned (stored in .kaggle-run.json) unless the caller names one explicitly."""
    if given and given != DEFAULT_SLUG:
        return given
    if STATE.exists():
        return json.loads(STATE.read_text(encoding="utf-8")).get("slug", given or DEFAULT_SLUG)
    return given or DEFAULT_SLUG


def creds() -> tuple[str, str]:
    user, key = os.environ.get("KAGGLE_USERNAME"), os.environ.get("KAGGLE_KEY")
    if not (user and key):
        p = Path(os.environ.get("KAGGLE_CONFIG_DIR", Path.home() / ".kaggle")) / "kaggle.json"
        if not p.exists():
            raise SystemExit(f"no Kaggle credentials: set KAGGLE_USERNAME/KAGGLE_KEY or create {p}")
        cfg = json.loads(p.read_text(encoding="utf-8"))
        user, key = cfg.get("username"), cfg.get("key")
    if not (user and key):
        raise SystemExit("Kaggle credentials are incomplete (need username and key)")
    return user, key


def api(method: str, path: str, **kw) -> httpx.Response:
    return httpx.request(method, BASE + path, auth=creds(), timeout=kw.pop("timeout", 120), follow_redirects=True, **kw)


def git_commit() -> str:
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()


KERNEL_SCRIPT = '''\
"""Generated by tools/kaggle_bench.py — do not edit on Kaggle, edit the generator."""
import os, subprocess, sys, shutil, pathlib, json, time

REPO = {repo!r}
COMMIT = {commit!r}
MODELS = {models!r}
BATCH_SIZES = {batch_sizes!r}
LIMIT = {limit!r}
SWEEP_SECONDS = {sweep_seconds!r}

SRC = "/tmp/st"
DATA = "/tmp/st-data"
OUT = "/kaggle/working/results"
os.environ["ST_DATA_DIR"] = DATA
os.environ["HF_HOME"] = DATA + "/hf"
os.environ["PYTHONUNBUFFERED"] = "1"

def run(cmd, **kw):
    print("+", cmd, flush=True)
    r = subprocess.run(cmd, shell=True, **kw)
    if r.returncode != 0:
        raise SystemExit(f"command failed ({{r.returncode}}): {{cmd}}")

t0 = time.time()
import torch
print("torch", torch.__version__, "cuda", torch.cuda.is_available(),
      torch.cuda.get_device_name(0) if torch.cuda.is_available() else "-", flush=True)
if not torch.cuda.is_available():
    raise SystemExit("no GPU on this kernel: enable the GPU accelerator")

run(f"git clone --quiet --filter=blob:none {{REPO}} {{SRC}}")
run(f"git -C {{SRC}} checkout --quiet {{COMMIT}}")
# deps the Kaggle image may lack; torch/torchvision/timm come with the image
run(f"{{sys.executable}} -m pip install -q --no-deps -e {{SRC}}/common -e {{SRC}}/inference -e {{SRC}}/eval")
run(f"{{sys.executable}} -m pip install -q pydantic-settings einops kornia 'transparent-background==1.3.4' --no-deps")
run(f"{{sys.executable}} -m pip install -q easydict pyyaml")

# Regenerate the benchmark set (deterministic from its seed) and fetch only the weights this run needs.
run(f"{{sys.executable}} -m st_eval.synth --out {{DATA}}/data/bench/{dataset} --n 200 --seed 1403", cwd=SRC)
run(f"{{sys.executable}} tools/tasks.py weights {weight_models}", cwd=SRC)

pathlib.Path(OUT).mkdir(parents=True, exist_ok=True)
cmd = (f"{{sys.executable}} -m st_eval.bench --dataset {{DATA}}/data/bench/{dataset} --out {{OUT}} "
       f"--models {{MODELS}} --batch-sizes {{BATCH_SIZES}} --sweep-seconds {{SWEEP_SECONDS}} "
       f"--report {{OUT}}/results.md")
if LIMIT:
    cmd += f" --limit {{LIMIT}}"
run(cmd, cwd=SRC)

# Kaggle's output *files* live on a Google CDN that is blocked from Iran (403), but the kernel LOG
# comes back fine — so results travel home as gzipped base64 chunks on stdout.
import base64, gzip
for p in [pathlib.Path(OUT, "run.json")] + sorted(pathlib.Path(OUT, "models").glob("*.json")):
    if not p.exists():
        continue
    enc = base64.b64encode(gzip.compress(p.read_bytes(), 9)).decode()
    chunks = [enc[i:i + 6000] for i in range(0, len(enc), 6000)]
    for i, c in enumerate(chunks):
        print(f"@@RESULT {{p.name}} {{i}} {{c}}", flush=True)
    print(f"@@RESULT_END {{p.name}} {{len(chunks)}}", flush=True)
print("TOTAL MINUTES", round((time.time() - t0) / 60, 1), flush=True)
'''


def base_model_names(models: str) -> list[str]:
    """"birefnet:fp16@1536#24,ben2_base" -> ["birefnet", "ben2_base"] (deduped, order kept)."""
    out: list[str] = []
    for spec in models.split(","):
        name = spec.strip().split(":")[0].split("@")[0].split("#")[0]
        if name and name not in out:
            out.append(name)
    return out


def build_script(models: str, batch_sizes: str, limit: int | None, sweep_seconds: float, commit: str) -> str:
    return KERNEL_SCRIPT.format(repo=REPO_URL, commit=commit, models=models, batch_sizes=batch_sizes,
                                limit=limit, sweep_seconds=sweep_seconds, dataset=DATASET_NAME,
                                weight_models=" ".join(base_model_names(models)))


def push(args) -> None:
    user, _ = creds()
    commit = args.commit or git_commit()
    local_head = git_commit()
    if commit == local_head:
        remote = subprocess.run(["git", "branch", "-r", "--contains", commit], cwd=ROOT, capture_output=True, text=True).stdout
        if "origin/" not in remote:
            raise SystemExit(f"commit {commit[:8]} is not pushed to GitHub yet — `git push` first, "
                             "otherwise Kaggle will benchmark older code")
    body = {
        "id": None,
        "slug": f"{user}/{args.slug}",
        "newTitle": args.title,
        "text": build_script(args.models, args.batch_sizes, args.limit, args.sweep_seconds, commit),
        "language": "python",
        "kernelType": "script",
        "isPrivate": True,
        "enableGpu": not args.cpu,
        "enableTpu": False,
        "enableInternet": True,  # needed to clone the repo and download weights
        "datasetDataSources": [],
        "competitionDataSources": [],
        "kernelDataSources": [],
        "modelDataSources": [],
        "categoryIds": [],
        "docker": "latest",
    }
    r = api("POST", "/kernels/push", json=body)
    data = r.json() if r.status_code == 200 else {}
    if r.status_code != 200 or data.get("error"):
        raise SystemExit(f"push failed: {r.status_code} {r.text[:400]}")
    url = data.get("url") or ""
    real_slug = (data.get("ref") or url).rstrip("/").split("/")[-1] or args.slug
    remember_slug(real_slug, url, commit)
    print(f"pushed version {data.get('versionNumber')} at commit {commit[:8]}")
    print(f"  {url}")
    print(f"  GPU={'off' if args.cpu else 'on'}  models={args.models}")
    if real_slug != args.slug:
        print(f"  note: Kaggle slugified the title -> '{real_slug}' (recorded in .kaggle-run.json)")
    print("poll with: python tools/kaggle_bench.py status --wait 90")


def status(args) -> None:
    user, _ = creds()
    slug = resolve_slug(args.slug)
    deadline = time.time() + args.wait * 60
    while True:
        r = api("GET", "/kernels/status", params={"userName": user, "kernelSlug": slug})
        s = r.json() if r.status_code == 200 else {"status": f"http {r.status_code}"}
        print(time.strftime("%H:%M:%S"), s.get("status"), s.get("failureMessage") or "")
        if s.get("status") in ("complete", "error", "cancelAcknowledged") or time.time() >= deadline:
            return
        time.sleep(args.poll)


def fetch(args) -> None:
    user, _ = creds()
    slug = resolve_slug(args.slug)
    r = api("GET", "/kernels/output", params={"userName": user, "kernelSlug": slug}, timeout=300)
    if r.status_code != 200:
        raise SystemExit(f"output not available: {r.status_code} {r.text[:300]}")
    data = r.json()
    dest = Path(args.out or ROOT / "eval" / "runs" / f"kaggle-{DATASET_NAME}")
    (dest / "models").mkdir(parents=True, exist_ok=True)
    n = 0
    log = data.get("log")
    entries = (json.loads(log) if isinstance(log, str) else log) or []
    stdout = "".join(str(e.get("data", "")) for e in entries if e.get("stream_name") == "stdout")

    # Primary path: results embedded in the log (the output-file CDN is blocked from Iran).
    parts: dict[str, dict[int, str]] = {}
    expected: dict[str, int] = {}
    for line in stdout.splitlines():
        if line.startswith("@@RESULT "):
            _, name, idx, chunk = line.split(" ", 3)
            parts.setdefault(name, {})[int(idx)] = chunk.strip()
        elif line.startswith("@@RESULT_END "):
            _, name, count = line.split(" ", 2)
            expected[name] = int(count)
    import base64 as _b64, gzip as _gz

    for name, chunks in parts.items():
        want = expected.get(name, len(chunks))
        if len(chunks) != want:
            print(f"  ! {name}: {len(chunks)}/{want} chunks (log truncated), skipping")
            continue
        blob = "".join(chunks[i] for i in sorted(chunks))
        try:
            raw = _gz.decompress(_b64.b64decode(blob))
        except Exception as e:
            print(f"  ! {name}: could not decode ({e})")
            continue
        target = dest / name if name == "run.json" else dest / "models" / name
        target.write_bytes(raw)
        n += 1
        print(f"  {name} <- log ({len(raw)} bytes)")

    # Secondary: try the CDN files too; they work outside blocked regions.
    for f in data.get("files", []):
        name, url = f.get("fileName"), f.get("url")
        if not url or name.startswith("model_") or "/models/" in name:
            continue
        try:
            resp = httpx.get(url, auth=creds(), timeout=300, follow_redirects=True)
            if resp.status_code != 200 or resp.content[:1] == b"\n<":
                continue
            target = dest / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(resp.content)
            n += 1
            print(f"  {name} <- cdn ({len(resp.content)} bytes)")
        except httpx.HTTPError:
            continue
    if log:
        entries = json.loads(log) if isinstance(log, str) else log
        lines = [f"[{e.get('time', 0):8.2f}] {e.get('stream_name', ''):6} {str(e.get('data', '')).rstrip()}"
                 for e in entries] if isinstance(entries, list) else [str(entries)]
        (dest / "kernel.log").write_text("\n".join(lines), encoding="utf-8")
        print(f"  log -> {dest / 'kernel.log'} ({len(lines)} lines)")
    print(f"{n} files into {dest}")
    print(f"render with: python -m st_eval.report {dest} --out eval/results.md")


def delete(args) -> None:
    user, _ = creds()
    r = api("POST", "/kernels/delete", json={"userName": user, "kernelSlug": args.slug})
    print(r.status_code, r.text[:200])


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--slug", default=DEFAULT_SLUG)

    p = sub.add_parser("push", parents=[common], help="create/update the kernel and queue a run")
    p.add_argument("--title", default="seller tooling bench", help="Kaggle derives the slug from this")
    # On a tensor-core GPU the registry default is already fp16, so the ":fp32" rows are the comparison.
    p.add_argument("--models", default="birefnet_lite,birefnet_lite:fp32,birefnet,birefnet:fp32,birefnet_dynamic,"
                                       "ben2_base,inspyrenet_base,inspyrenet_fast,birefnet_hr#24")
    p.add_argument("--batch-sizes", default="1,4,8,16")
    p.add_argument("--sweep-seconds", type=float, default=20.0)
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--commit", default=None, help="defaults to local HEAD (must be pushed)")
    p.add_argument("--cpu", action="store_true", help="no GPU (for testing the plumbing)")
    p.set_defaults(func=push)

    p = sub.add_parser("status", parents=[common])
    p.add_argument("--poll", type=float, default=30)
    p.add_argument("--wait", type=float, default=0, help="keep polling this many minutes")
    p.set_defaults(func=status)

    p = sub.add_parser("fetch", parents=[common])
    p.add_argument("--out", default=None)
    p.set_defaults(func=fetch)

    p = sub.add_parser("delete", parents=[common])
    p.set_defaults(func=delete)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
