#!/usr/bin/env python
"""Run the benchmark on a Kaggle GPU and pull the results back.

Why this exists: the dev laptop has a GTX 1650 (4 GB, fp16 broken, VRAM spills into system RAM).
Kaggle gives a 16 GB T4/P100 on Linux, which produces real batch sweeps, a real fp16-vs-fp32
answer, and real OOM instead of silent paging. It is still not the target 24 GB card (H-001).

    python tools/kaggle_bench.py push      # create/update the kernel and start it
    python tools/kaggle_bench.py status    # poll
    python tools/kaggle_bench.py fetch     # download results into eval/runs/<name>/
    python tools/kaggle_bench.py delete    # remove the kernel from your account

Credentials: this talks to the **legacy** REST API at www.kaggle.com/api/v1, not the newer
api.kaggle.com host, which is network-blocked from Iran (403 from Google's frontend). That also
makes the new `KGAT_...` tokens unusable, because the CLI validates them against the blocked host.
So we use the classic username + key from ~/.kaggle/kaggle.json or KAGGLE_USERNAME/KAGGLE_KEY.

The kernel is **private** and clones this repo at a pinned commit, so whatever you push to GitHub
is what gets benchmarked.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://www.kaggle.com/api/v1"
REPO_URL = "https://github.com/Pouyops/Seller_Tooling.git"
DEFAULT_SLUG = "seller-tooling-bench"
DATASET_NAME = "synth-v1-s1403-n200"


def creds() -> tuple[str, str]:
    user, key = os.environ.get("KAGGLE_USERNAME"), os.environ.get("KAGGLE_KEY")
    if not (user and key):
        p = Path(os.environ.get("KAGGLE_CONFIG_DIR", Path.home() / ".kaggle")) / "kaggle.json"
        if not p.exists():
            raise SystemExit(f"no Kaggle credentials: set KAGGLE_USERNAME/KAGGLE_KEY or create {p}")
        cfg = json.loads(p.read_text(encoding="utf-8"))
        user, key = cfg.get("username"), cfg.get("key")
    if not (user and key):
        raise SystemExit("Kaggle credentials are incomplete (need username and key)")
    return user, key


def api(method: str, path: str, **kw) -> httpx.Response:
    return httpx.request(method, BASE + path, auth=creds(), timeout=kw.pop("timeout", 120), follow_redirects=True, **kw)


def git_commit() -> str:
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()


KERNEL_SCRIPT = '''\
"""Generated by tools/kaggle_bench.py — do not edit on Kaggle, edit the generator."""
import os, subprocess, sys, shutil, pathlib, json, time

REPO = {repo!r}
COMMIT = {commit!r}
MODELS = {models!r}
BATCH_SIZES = {batch_sizes!r}
LIMIT = {limit!r}
SWEEP_SECONDS = {sweep_seconds!r}

SRC = "/tmp/st"
DATA = "/tmp/st-data"
OUT = "/kaggle/working/results"
os.environ["ST_DATA_DIR"] = DATA
os.environ["HF_HOME"] = DATA + "/hf"
os.environ["PYTHONUNBUFFERED"] = "1"

def run(cmd, **kw):
    print("+", cmd, flush=True)
    r = subprocess.run(cmd, shell=True, **kw)
    if r.returncode != 0:
        raise SystemExit(f"command failed ({{r.returncode}}): {{cmd}}")

t0 = time.time()
import torch
print("torch", torch.__version__, "cuda", torch.cuda.is_available(),
      torch.cuda.get_device_name(0) if torch.cuda.is_available() else "-", flush=True)
if not torch.cuda.is_available():
    raise SystemExit("no GPU on this kernel: enable the GPU accelerator")

run(f"git clone --quiet --filter=blob:none {{REPO}} {{SRC}}")
run(f"git -C {{SRC}} checkout --quiet {{COMMIT}}")
# deps the Kaggle image may lack; torch/torchvision/timm come with the image
run(f"{{sys.executable}} -m pip install -q --no-deps -e {{SRC}}/common -e {{SRC}}/inference -e {{SRC}}/eval")
run(f"{{sys.executable}} -m pip install -q pydantic-settings einops kornia 'transparent-background==1.3.4' --no-deps")
run(f"{{sys.executable}} -m pip install -q easydict pyyaml")

# Regenerate the benchmark set (deterministic from its seed) and fetch only the weights this run needs.
run(f"{{sys.executable}} -m st_eval.synth --out {{DATA}}/data/bench/{dataset} --n 200 --seed 1403", cwd=SRC)
run(f"{{sys.executable}} tools/tasks.py weights {weight_models}", cwd=SRC)

pathlib.Path(OUT).mkdir(parents=True, exist_ok=True)
cmd = (f"{{sys.executable}} -m st_eval.bench --dataset {{DATA}}/data/bench/{dataset} --out {{OUT}} "
       f"--models {{MODELS}} --batch-sizes {{BATCH_SIZES}} --sweep-seconds {{SWEEP_SECONDS}} "
       f"--report {{OUT}}/results.md")
if LIMIT:
    cmd += f" --limit {{LIMIT}}"
run(cmd, cwd=SRC)

# Flatten the per-model JSON next to the report so `fetch` can grab them from the output listing.
for p in pathlib.Path(OUT, "models").glob("*.json"):
    shutil.copy(p, pathlib.Path(OUT, f"model_{{p.name}}"))
print("TOTAL MINUTES", round((time.time() - t0) / 60, 1), flush=True)
'''


def base_model_names(models: str) -> list[str]:
    """"birefnet:fp16@1536#24,ben2_base" -> ["birefnet", "ben2_base"] (deduped, order kept)."""
    out: list[str] = []
    for spec in models.split(","):
        name = spec.strip().split(":")[0].split("@")[0].split("#")[0]
        if name and name not in out:
            out.append(name)
    return out


def build_script(models: str, batch_sizes: str, limit: int | None, sweep_seconds: float, commit: str) -> str:
    return KERNEL_SCRIPT.format(repo=REPO_URL, commit=commit, models=models, batch_sizes=batch_sizes,
                                limit=limit, sweep_seconds=sweep_seconds, dataset=DATASET_NAME,
                                weight_models=" ".join(base_model_names(models)))


def push(args) -> None:
    user, _ = creds()
    commit = args.commit or git_commit()
    local_head = git_commit()
    if commit == local_head:
        remote = subprocess.run(["git", "branch", "-r", "--contains", commit], cwd=ROOT, capture_output=True, text=True).stdout
        if "origin/" not in remote:
            raise SystemExit(f"commit {commit[:8]} is not pushed to GitHub yet — `git push` first, "
                             "otherwise Kaggle will benchmark older code")
    body = {
        "id": None,
        "slug": f"{user}/{args.slug}",
        "newTitle": args.title,
        "text": build_script(args.models, args.batch_sizes, args.limit, args.sweep_seconds, commit),
        "language": "python",
        "kernelType": "script",
        "isPrivate": True,
        "enableGpu": not args.cpu,
        "enableTpu": False,
        "enableInternet": True,  # needed to clone the repo and download weights
        "datasetDataSources": [],
        "competitionDataSources": [],
        "kernelDataSources": [],
        "modelDataSources": [],
        "categoryIds": [],
        "docker": "latest",
    }
    r = api("POST", "/kernels/push", json=body)
    data = r.json() if r.status_code == 200 else {}
    if r.status_code != 200 or data.get("error"):
        raise SystemExit(f"push failed: {r.status_code} {r.text[:400]}")
    print(f"pushed version {data.get('versionNumber')} at commit {commit[:8]}")
    print(f"  {data.get('url')}")
    print(f"  GPU={'off' if args.cpu else 'on'}  models={args.models}")
    print(f"poll with: python tools/kaggle_bench.py status --slug {args.slug}")


def status(args) -> None:
    user, _ = creds()
    deadline = time.time() + args.wait * 60
    while True:
        r = api("GET", "/kernels/status", params={"userName": user, "kernelSlug": args.slug})
        s = r.json() if r.status_code == 200 else {"status": f"http {r.status_code}"}
        print(time.strftime("%H:%M:%S"), s.get("status"), s.get("failureMessage") or "")
        if s.get("status") in ("complete", "error", "cancelAcknowledged") or time.time() >= deadline:
            return
        time.sleep(args.poll)


def fetch(args) -> None:
    user, _ = creds()
    r = api("GET", "/kernels/output", params={"userName": user, "kernelSlug": args.slug}, timeout=300)
    if r.status_code != 200:
        raise SystemExit(f"output not available: {r.status_code} {r.text[:300]}")
    data = r.json()
    dest = Path(args.out or ROOT / "eval" / "runs" / f"kaggle-{DATASET_NAME}")
    (dest / "models").mkdir(parents=True, exist_ok=True)
    n = 0
    for f in data.get("files", []):
        name, url = f.get("fileName"), f.get("url")
        if not url:
            continue
        body = httpx.get(url, auth=creds(), timeout=300, follow_redirects=True).content
        target = dest / "models" / name[len("model_"):] if name.startswith("model_") else dest / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(body)
        n += 1
        print(f"  {name} -> {target.relative_to(ROOT) if ROOT in target.parents else target} ({len(body)} bytes)")
    log = data.get("log")
    if log:
        entries = json.loads(log) if isinstance(log, str) else log
        lines = [f"[{e.get('time', 0):8.2f}] {e.get('stream_name', ''):6} {str(e.get('data', '')).rstrip()}"
                 for e in entries] if isinstance(entries, list) else [str(entries)]
        (dest / "kernel.log").write_text("\n".join(lines), encoding="utf-8")
        print(f"  log -> {dest / 'kernel.log'} ({len(lines)} lines)")
    print(f"{n} files into {dest}")
    print(f"render with: python -m st_eval.report {dest} --out eval/results.md")


def delete(args) -> None:
    user, _ = creds()
    r = api("POST", "/kernels/delete", json={"userName": user, "kernelSlug": args.slug})
    print(r.status_code, r.text[:200])


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--slug", default=DEFAULT_SLUG)

    p = sub.add_parser("push", parents=[common], help="create/update the kernel and queue a run")
    p.add_argument("--title", default="Seller Tooling benchmark")
    p.add_argument("--models", default="birefnet_lite,birefnet,birefnet_dynamic,ben2_base,inspyrenet_base,inspyrenet_fast,"
                                       "birefnet_lite:fp16,birefnet:fp16,birefnet_hr#24")
    p.add_argument("--batch-sizes", default="1,4,8,16")
    p.add_argument("--sweep-seconds", type=float, default=20.0)
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--commit", default=None, help="defaults to local HEAD (must be pushed)")
    p.add_argument("--cpu", action="store_true", help="no GPU (for testing the plumbing)")
    p.set_defaults(func=push)

    p = sub.add_parser("status", parents=[common])
    p.add_argument("--poll", type=float, default=30)
    p.add_argument("--wait", type=float, default=0, help="keep polling this many minutes")
    p.set_defaults(func=status)

    p = sub.add_parser("fetch", parents=[common])
    p.add_argument("--out", default=None)
    p.set_defaults(func=fetch)

    p = sub.add_parser("delete", parents=[common])
    p.set_defaults(func=delete)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
